### ISSUE TITLE
Dev Dependencies

### ISSUE THREAD

**Issue by KryptoBeard** [Basaingeal/Razor.SweetAlert2#1254]
Hello, I'm trying to contribute, but I'm not sure how to get this to build properly. Webpack doesn't like the dependencies. Is there anything special i need to get this to build and output the javascript/typescript/css properly? .Net library builds fine.

**Comment by Basaingeal** [comment]
Hey there. Thanks for your interest in contributing. 

There shouldn't be too much trouble with building. The CI pipeline runs a build every time a change is made, so it should work without too much difficulty.

Are you using yarn or npm? This project has been developed using yarn v1, so that might work better for you.

Can you share the webpack error that you are seeing?
