### ISSUE TITLE
swal2-input conficts with open Bootstrap 4 modal

### ISSUE THREAD

**Issue by RestoreMonarchy** [Basaingeal/Razor.SweetAlert2#677]
**Describe the bug**
When I fire SweetAlert2 with input, the input is disabled and I cannot type in it

**To Reproduce**
Method triggered on load and button onclick
```cs
private async Task ConfirmRemoveItemAsync(MarketItem marketItem)
{
    await Swal.FireAsync(new SweetAlertOptions()
    {
        Title = "Are you sure?",
        Text = $"{marketItem.Id} ({marketItem.ItemName}) will be moved to your buyings",
        Icon = SweetAlertIcon.Warning,
        ShowCancelButton = true,
        ConfirmButtonText = "Yes, remove it!"
    }).ContinueWith(async (swalTask) => 
    {
        if (Convert.ToBoolean(swalTask.Result.Value))
        {
            await RemoveItemAsync(marketItem);
        }
    });
}
```

**Expected behavior**
I should be able to write in input even if Bootstrap modal is opened

**Screenshots**
OnInitialized when Bootstrap modal isn't opened
![image](https://user-images.githubusercontent.com/35507241/81494286-fbce0c80-92a7-11ea-9b40-a86e901a8bfa.png)

When triggered by "Change Price" button when Bootstrap modal is opened
![image](https://user-images.githubusercontent.com/35507241/81494305-21f3ac80-92a8-11ea-876a-92025042aa8e.png)

**Comment by RestoreMonarchy** [comment]
For now I made it close bootstrap modal when the Change Price button is clicked and it works then.

![2020-05-10_10-27-50](https://user-images.githubusercontent.com/35507241/81494418-21a7e100-92a9-11ea-99e7-950da361145c.gif)

**Comment by Basaingeal** [comment]
I'll take a look at this. However, I'm almost positive that this is a problem with the upstream's `sweetalert2` JavaScript library, and not with this Blazor wrapper. I know this because I ran into this problem myself on another project when I was using both Bootstrap and SweetAlert.

I would recommend doing a quick test using the JavaScript sweetalert2 library, and if you see the problem there too, open an issue for there instead. If you don't see the issue there, then let me know because it's somehow restricted to just this wrapper's implementation.

**Comment by RestoreMonarchy** [comment]
Hey @Basaingeal thanks for reply,
It looks like you're right, there's the same issue with JavaScript sweetalert2 library. I tried it like this: https://codepen.io/MichaelCrow/pen/MWaBVEq

I'm gonna report it in JavaScript SweetAlert2 repo issues.

**Comment by Basaingeal** [comment]
Closing due to closure of issue in upstream library.
